[package]
name = "linux_kernel_module"
version = "0.1.0"
edition = "2024"
authors = ["Hotz99 @ github.com"]

[dependencies]
anyhow = "1.0.86"
nix = { version = "0.29.0", features = ["ioctl"] }
sysinfo = "0.30.12"
