[package]
name = "baldwin"
version = "0.1.0"
edition = "2021"

#build = "src/build.rs"

[build-dependencies]
bindgen = "0.69.4"

[dependencies]
anyhow = "1.0.86"
nix = { version = "0.29.0", features = ["ioctl"] }
sysinfo = "0.30.12"
input = "0.9.0"
